from __future__ import annotations

from core.models import CandidateTest, ClinicalDecisionContext, LikelihoodRatioRange
from evidence.integration import enrich_candidate_test
from evidence.registry_loader import LREntry


TEST_CATALOG: dict[str, CandidateTest] = {
    "ecg": CandidateTest(
        slug="ecg",
        name="12-lead ECG",
        target_diagnoses=["acs"],
        diagnosis_lrs={"acs": LikelihoodRatioRange(positive_lr=3.4, negative_lr=0.5)},
        target_states=["thrombotic_ischemic_tendency", "impaired_contractility"],
        state_lrs={
            "thrombotic_ischemic_tendency": LikelihoodRatioRange(positive_lr=2.8, negative_lr=0.72),
            "impaired_contractility": LikelihoodRatioRange(positive_lr=1.8, negative_lr=0.88),
        },
        direct_cost=15,
        downstream_cost=0,
        actionability=1.0,
        urgency_modifier=1.4,
        bedside=True,
        mechanistic_note="Helps distinguish ischemic injury and low-forward-flow cardiogenic physiology.",
        provenance_refs=["registry:acs_symptom_profile", "cost:starter_us_hospital"],
    ),
    "hs_troponin": CandidateTest(
        slug="hs_troponin",
        name="High-sensitivity troponin",
        target_diagnoses=["acs"],
        diagnosis_lrs={"acs": LikelihoodRatioRange(positive_lr=4.5, negative_lr=0.4)},
        target_states=["thrombotic_ischemic_tendency", "impaired_contractility"],
        state_lrs={
            "thrombotic_ischemic_tendency": LikelihoodRatioRange(positive_lr=3.3, negative_lr=0.7),
            "impaired_contractility": LikelihoodRatioRange(positive_lr=2.2, negative_lr=0.82),
        },
        direct_cost=45,
        downstream_cost=120,
        actionability=0.95,
        bedside=True,
        mechanistic_note="Troponin delta refines ischemic injury and secondary pump-failure hypotheses.",
        provenance_refs=["registry:acs_symptom_profile", "cost:starter_us_hospital"],
    ),
    "d_dimer": CandidateTest(
        slug="d_dimer",
        name="D-dimer",
        target_diagnoses=["pe"],
        diagnosis_lrs={"pe": LikelihoodRatioRange(positive_lr=2.2, negative_lr=0.2)},
        target_states=["thrombotic_ischemic_tendency", "obstructive_physiology"],
        state_lrs={
            "thrombotic_ischemic_tendency": LikelihoodRatioRange(positive_lr=1.8, negative_lr=0.76),
            "obstructive_physiology": LikelihoodRatioRange(positive_lr=1.55, negative_lr=0.82),
        },
        direct_cost=40,
        downstream_cost=0,
        actionability=0.7,
        bedside=True,
        mechanistic_note="Useful when thrombotic or obstructive physiology is plausible and bleeding risk is low.",
        provenance_refs=["study:d_dimer_pe", "cost:starter_us_hospital"],
    ),
    "cta_pe": CandidateTest(
        slug="cta_pe",
        name="CT Pulmonary Angiography",
        target_diagnoses=["pe"],
        diagnosis_lrs={"pe": LikelihoodRatioRange(positive_lr=8.0, negative_lr=0.1)},
        target_states=["obstructive_physiology", "thrombotic_ischemic_tendency"],
        state_lrs={
            "obstructive_physiology": LikelihoodRatioRange(positive_lr=4.8, negative_lr=0.45),
            "thrombotic_ischemic_tendency": LikelihoodRatioRange(positive_lr=2.5, negative_lr=0.7),
        },
        direct_cost=850,
        downstream_cost=300,
        radiation=0.6,
        nephrotoxicity=0.35,
        actionability=0.95,
        mechanistic_note="High-yield structural clarification for obstructive pulmonary vascular physiology.",
        provenance_refs=["study:cta_pe", "cost:starter_us_hospital", "risk:contrast_ckd"],
    ),
    "cxr": CandidateTest(
        slug="cxr",
        name="Chest Radiograph",
        target_diagnoses=["pneumonia", "heart_failure"],
        diagnosis_lrs={
            "pneumonia": LikelihoodRatioRange(positive_lr=3.0, negative_lr=0.4),
            "heart_failure": LikelihoodRatioRange(positive_lr=1.8, negative_lr=0.7),
        },
        target_states=["venous_congestion", "distributive_physiology"],
        state_lrs={
            "venous_congestion": LikelihoodRatioRange(positive_lr=1.8, negative_lr=0.78),
            "distributive_physiology": LikelihoodRatioRange(positive_lr=1.4, negative_lr=0.88),
        },
        direct_cost=120,
        downstream_cost=0,
        radiation=0.15,
        actionability=0.75,
        mechanistic_note="Helps separate edema/congestion from focal infectious or inflammatory lung involvement.",
        provenance_refs=["study:cxr_pneumonia", "cost:starter_us_hospital"],
    ),
    "bnp": CandidateTest(
        slug="bnp",
        name="BNP",
        target_diagnoses=["heart_failure"],
        diagnosis_lrs={"heart_failure": LikelihoodRatioRange(positive_lr=3.1, negative_lr=0.3)},
        target_states=["venous_congestion", "fluid_intolerance", "impaired_contractility"],
        state_lrs={
            "venous_congestion": LikelihoodRatioRange(positive_lr=2.5, negative_lr=0.62),
            "fluid_intolerance": LikelihoodRatioRange(positive_lr=2.0, negative_lr=0.7),
            "impaired_contractility": LikelihoodRatioRange(positive_lr=1.6, negative_lr=0.84),
        },
        direct_cost=90,
        downstream_cost=0,
        actionability=0.8,
        bedside=True,
        mechanistic_note="Improves confidence in congestion-dominant and fluid-intolerant physiology.",
        provenance_refs=["study:bnp_hf", "cost:starter_us_hospital"],
    ),
    "cbc": CandidateTest(
        slug="cbc",
        name="Complete blood count",
        target_diagnoses=["upper_gi_bleed"],
        diagnosis_lrs={"upper_gi_bleed": LikelihoodRatioRange(positive_lr=2.6, negative_lr=0.75)},
        target_states=["hemorrhagic_tendency_active_blood_loss", "low_effective_arterial_volume"],
        state_lrs={
            "hemorrhagic_tendency_active_blood_loss": LikelihoodRatioRange(positive_lr=2.2, negative_lr=0.82),
            "low_effective_arterial_volume": LikelihoodRatioRange(positive_lr=1.55, negative_lr=0.9),
        },
        direct_cost=20,
        downstream_cost=40,
        actionability=1.0,
        urgency_modifier=1.55,
        bedside=True,
        mechanistic_note="Hemoglobin trajectory helps quantify active blood loss and preload depletion.",
        provenance_refs=["study:cbc_gi_bleed", "cost:starter_us_hospital"],
    ),
    "pt_inr": CandidateTest(
        slug="pt_inr",
        name="PT/INR",
        target_diagnoses=["upper_gi_bleed"],
        diagnosis_lrs={"upper_gi_bleed": LikelihoodRatioRange(positive_lr=2.1, negative_lr=0.82)},
        target_states=["hemorrhagic_tendency_active_blood_loss", "medication_toxicity_effect"],
        state_lrs={
            "hemorrhagic_tendency_active_blood_loss": LikelihoodRatioRange(positive_lr=1.8, negative_lr=0.9),
            "medication_toxicity_effect": LikelihoodRatioRange(positive_lr=2.6, negative_lr=0.8),
        },
        direct_cost=18,
        downstream_cost=60,
        actionability=1.0,
        urgency_modifier=1.6,
        bedside=True,
        mechanistic_note="Clarifies whether anticoagulation toxicity is amplifying hemorrhagic physiology.",
        provenance_refs=["study:warfarin_bleeding", "cost:starter_us_hospital"],
    ),
    "type_screen": CandidateTest(
        slug="type_screen",
        name="Type and screen",
        target_diagnoses=["upper_gi_bleed"],
        diagnosis_lrs={"upper_gi_bleed": LikelihoodRatioRange(positive_lr=1.7, negative_lr=0.95)},
        target_states=["hemorrhagic_tendency_active_blood_loss"],
        state_lrs={"hemorrhagic_tendency_active_blood_loss": LikelihoodRatioRange(positive_lr=1.45, negative_lr=0.98)},
        direct_cost=85,
        downstream_cost=120,
        actionability=1.0,
        urgency_modifier=1.7,
        bedside=True,
        mechanistic_note="Actionability is high when blood-loss physiology may require transfusion support.",
        provenance_refs=["study:warfarin_bleeding", "cost:starter_us_hospital"],
    ),
    "upper_endoscopy": CandidateTest(
        slug="upper_endoscopy",
        name="Upper endoscopy",
        target_diagnoses=["upper_gi_bleed"],
        diagnosis_lrs={"upper_gi_bleed": LikelihoodRatioRange(positive_lr=6.5, negative_lr=0.28)},
        target_states=["hemorrhagic_tendency_active_blood_loss", "medication_toxicity_effect"],
        state_lrs={
            "hemorrhagic_tendency_active_blood_loss": LikelihoodRatioRange(positive_lr=3.8, negative_lr=0.55),
            "medication_toxicity_effect": LikelihoodRatioRange(positive_lr=1.35, negative_lr=0.95),
        },
        direct_cost=2200,
        downstream_cost=450,
        invasiveness=0.45,
        bleed_risk=0.2,
        logistic_burden=0.35,
        actionability=1.0,
        urgency_modifier=1.45,
        mechanistic_note="Definitive structural clarification for active upper GI bleeding physiology.",
        provenance_refs=["registry:upper_gi_bleed_profile", "cost:starter_us_hospital"],
    ),
    "bedside_echo": CandidateTest(
        slug="bedside_echo",
        name="Bedside echocardiography",
        target_diagnoses=["heart_failure", "acs", "pe"],
        diagnosis_lrs={
            "heart_failure": LikelihoodRatioRange(positive_lr=2.6, negative_lr=0.62),
            "acs": LikelihoodRatioRange(positive_lr=1.5, negative_lr=0.9),
            "pe": LikelihoodRatioRange(positive_lr=1.7, negative_lr=0.88),
        },
        target_states=["impaired_contractility", "venous_congestion", "obstructive_physiology", "fluid_intolerance"],
        state_lrs={
            "impaired_contractility": LikelihoodRatioRange(positive_lr=3.1, negative_lr=0.64),
            "venous_congestion": LikelihoodRatioRange(positive_lr=2.0, negative_lr=0.82),
            "obstructive_physiology": LikelihoodRatioRange(positive_lr=2.3, negative_lr=0.8),
            "fluid_intolerance": LikelihoodRatioRange(positive_lr=1.8, negative_lr=0.86),
        },
        direct_cost=240,
        downstream_cost=80,
        actionability=0.95,
        urgency_modifier=1.35,
        bedside=True,
        mechanistic_note="High-yield bedside clarification of pump failure, congestion, and obstructive physiology.",
        provenance_refs=["mechanism:starter_registry", "cost:starter_us_hospital"],
    ),
    "plr_lvot_vti": CandidateTest(
        slug="plr_lvot_vti",
        name="PLR with LVOT VTI assessment",
        target_diagnoses=[],
        diagnosis_lrs={},
        target_states=["fluid_responsiveness", "fluid_intolerance", "low_effective_arterial_volume", "venous_congestion"],
        state_lrs={
            "fluid_responsiveness": LikelihoodRatioRange(positive_lr=3.0, negative_lr=0.58),
            "fluid_intolerance": LikelihoodRatioRange(positive_lr=0.58, negative_lr=1.45),
            "low_effective_arterial_volume": LikelihoodRatioRange(positive_lr=2.2, negative_lr=0.74),
            "venous_congestion": LikelihoodRatioRange(positive_lr=0.72, negative_lr=1.18),
        },
        direct_cost=85,
        downstream_cost=20,
        actionability=0.92,
        urgency_modifier=1.25,
        bedside=True,
        mechanistic_note="Clarifies whether preload augmentation is likely to help or harm.",
        provenance_refs=["mechanism:starter_registry", "cost:starter_us_hospital"],
    ),
    "repeat_hemoglobin": CandidateTest(
        slug="repeat_hemoglobin",
        name="Repeat hemoglobin trend",
        target_diagnoses=["upper_gi_bleed"],
        diagnosis_lrs={"upper_gi_bleed": LikelihoodRatioRange(positive_lr=2.0, negative_lr=0.85)},
        target_states=["hemorrhagic_tendency_active_blood_loss", "low_effective_arterial_volume"],
        state_lrs={
            "hemorrhagic_tendency_active_blood_loss": LikelihoodRatioRange(positive_lr=2.5, negative_lr=0.78),
            "low_effective_arterial_volume": LikelihoodRatioRange(positive_lr=1.65, negative_lr=0.9),
        },
        direct_cost=18,
        downstream_cost=30,
        actionability=0.92,
        urgency_modifier=1.4,
        bedside=True,
        mechanistic_note="Dynamic hemoglobin change is useful when ongoing blood loss remains uncertain.",
        provenance_refs=["mechanism:starter_registry", "cost:starter_us_hospital"],
    ),
}


def default_test_catalog(
    *,
    context: ClinicalDecisionContext | None = None,
    registry_entries: list[LREntry] | None = None,
) -> list[CandidateTest]:
    return [
        enrich_candidate_test(candidate, context=context, registry_entries=registry_entries)
        for candidate in TEST_CATALOG.values()
    ]
