from __future__ import annotations

from core.models import HypothesisEvidence, LikelihoodRatioRange


LR_CATALOG: dict[str, list[HypothesisEvidence]] = {
    "pe": [
        HypothesisEvidence(
            finding_key="pleuritic_chest_pain",
            label="Pleuritic chest pain",
            lr=LikelihoodRatioRange(positive_lr=1.8, negative_lr=0.8, positive_lr_low=1.2, positive_lr_high=2.4),
            rationale="Pleuritic pain increases suspicion for thromboembolic pleural irritation.",
            provenance_refs=["rule:wells_pe"],
        ),
        HypothesisEvidence(
            finding_key="tachycardia",
            label="Tachycardia",
            lr=LikelihoodRatioRange(positive_lr=1.7, negative_lr=0.7, positive_lr_low=1.1, positive_lr_high=2.3),
            rationale="Tachycardia is supportive but non-specific in PE suspicion.",
            provenance_refs=["rule:wells_pe"],
        ),
        HypothesisEvidence(
            finding_key="hypoxemia",
            label="Hypoxemia",
            lr=LikelihoodRatioRange(positive_lr=2.0, negative_lr=0.6, positive_lr_low=1.3, positive_lr_high=2.8),
            rationale="Gas exchange impairment supports clinically meaningful PE.",
            provenance_refs=["rule:wells_pe"],
        ),
        HypothesisEvidence(
            finding_key="rv_strain",
            label="RV strain",
            lr=LikelihoodRatioRange(positive_lr=3.2, negative_lr=0.65, positive_lr_low=2.2, positive_lr_high=4.3),
            rationale="RV strain materially supports an acute pulmonary vascular obstructive process.",
            provenance_refs=["rule:wells_pe", "mechanism:starter_registry"],
        ),
        HypothesisEvidence(
            finding_key="hemodynamic_instability",
            label="Hemodynamic instability",
            lr=LikelihoodRatioRange(positive_lr=1.8, negative_lr=0.82, positive_lr_low=1.2, positive_lr_high=2.5),
            rationale="Instability raises concern for high-risk PE when paired with compatible symptoms.",
            provenance_refs=["rule:wells_pe"],
        ),
        HypothesisEvidence(
            finding_key="fever",
            label="Fever",
            lr=LikelihoodRatioRange(positive_lr=0.7, negative_lr=1.1, positive_lr_low=0.5, positive_lr_high=0.9),
            rationale="Fever modestly lowers PE likelihood relative to infectious alternatives.",
            provenance_refs=["rule:wells_pe"],
        ),
    ],
    "pneumonia": [
        HypothesisEvidence(
            finding_key="fever",
            label="Fever",
            lr=LikelihoodRatioRange(positive_lr=2.1, negative_lr=0.5, positive_lr_low=1.5, positive_lr_high=2.8),
            rationale="Fever materially increases the likelihood of lower respiratory infection.",
            provenance_refs=["study:cxr_pneumonia"],
        ),
        HypothesisEvidence(
            finding_key="crackles",
            label="Focal crackles",
            lr=LikelihoodRatioRange(positive_lr=2.5, negative_lr=0.7, positive_lr_low=1.8, positive_lr_high=3.3),
            rationale="Focal auscultatory findings support parenchymal involvement.",
            provenance_refs=["study:cxr_pneumonia"],
        ),
        HypothesisEvidence(
            finding_key="purulent_sputum",
            label="Purulent sputum",
            lr=LikelihoodRatioRange(positive_lr=1.9, negative_lr=0.8, positive_lr_low=1.3, positive_lr_high=2.6),
            rationale="Purulent sputum increases the likelihood of bacterial pneumonia.",
            provenance_refs=["study:cxr_pneumonia"],
        ),
        HypothesisEvidence(
            finding_key="hypoxemia",
            label="Hypoxemia",
            lr=LikelihoodRatioRange(positive_lr=1.5, negative_lr=0.82, positive_lr_low=1.1, positive_lr_high=2.0),
            rationale="Hypoxemia supports clinically significant lower respiratory infection.",
            provenance_refs=["study:cxr_pneumonia"],
        ),
    ],
    "heart_failure": [
        HypothesisEvidence(
            finding_key="orthopnea",
            label="Orthopnea",
            lr=LikelihoodRatioRange(positive_lr=2.7, negative_lr=0.5, positive_lr_low=1.9, positive_lr_high=3.6),
            rationale="Orthopnea favors cardiogenic pulmonary congestion.",
            provenance_refs=["study:bnp_hf"],
        ),
        HypothesisEvidence(
            finding_key="crackles",
            label="Diffuse crackles",
            lr=LikelihoodRatioRange(positive_lr=2.0, negative_lr=0.7, positive_lr_low=1.3, positive_lr_high=2.8),
            rationale="Pulmonary edema physiology often presents with crackles.",
            provenance_refs=["study:bnp_hf"],
        ),
        HypothesisEvidence(
            finding_key="leg_edema",
            label="Leg edema",
            lr=LikelihoodRatioRange(positive_lr=1.8, negative_lr=0.8, positive_lr_low=1.2, positive_lr_high=2.5),
            rationale="Peripheral edema adds support for systemic congestion.",
            provenance_refs=["study:bnp_hf"],
        ),
        HypothesisEvidence(
            finding_key="elevated_jvp",
            label="Elevated JVP",
            lr=LikelihoodRatioRange(positive_lr=2.6, negative_lr=0.68, positive_lr_low=1.8, positive_lr_high=3.5),
            rationale="Elevated JVP strongly supports venous congestion from heart failure physiology.",
            provenance_refs=["study:bnp_hf", "mechanism:starter_registry"],
        ),
        HypothesisEvidence(
            finding_key="bnp_elevated",
            label="Elevated BNP/NT-proBNP",
            lr=LikelihoodRatioRange(positive_lr=3.2, negative_lr=0.45, positive_lr_low=2.2, positive_lr_high=4.4),
            rationale="Elevated natriuretic peptides support congestion and heart failure physiology.",
            provenance_refs=["study:bnp_hf"],
        ),
        HypothesisEvidence(
            finding_key="reduced_ef",
            label="Reduced ejection fraction",
            lr=LikelihoodRatioRange(positive_lr=3.8, negative_lr=0.6, positive_lr_low=2.6, positive_lr_high=5.0),
            rationale="Reduced EF materially supports a heart failure syndrome driven by impaired contractility.",
            provenance_refs=["mechanism:starter_registry"],
        ),
    ],
    "acs": [
        HypothesisEvidence(
            finding_key="pressure_chest_pain",
            label="Pressure-like chest pain",
            lr=LikelihoodRatioRange(positive_lr=2.2, negative_lr=0.7, positive_lr_low=1.5, positive_lr_high=2.9),
            rationale="Pressure-like chest discomfort supports ischemic chest pain.",
            provenance_refs=["registry:acs_symptom_profile"],
        ),
        HypothesisEvidence(
            finding_key="diaphoresis",
            label="Diaphoresis",
            lr=LikelihoodRatioRange(positive_lr=1.9, negative_lr=0.8, positive_lr_low=1.3, positive_lr_high=2.5),
            rationale="Diaphoresis increases concern for high-risk ischemic chest pain in the right context.",
            provenance_refs=["registry:acs_symptom_profile"],
        ),
        HypothesisEvidence(
            finding_key="pain_radiation",
            label="Radiation to arm or jaw",
            lr=LikelihoodRatioRange(positive_lr=2.1, negative_lr=0.8, positive_lr_low=1.4, positive_lr_high=2.8),
            rationale="Pain radiation to arm or jaw favors ischemic chest pain over pulmonary causes.",
            provenance_refs=["registry:acs_symptom_profile"],
        ),
        HypothesisEvidence(
            finding_key="troponin_positive",
            label="Positive troponin",
            lr=LikelihoodRatioRange(positive_lr=4.5, negative_lr=0.4, positive_lr_low=3.0, positive_lr_high=6.0),
            rationale="Troponin elevation strongly supports myocardial injury etiologies.",
            provenance_refs=["registry:acs_symptom_profile"],
        ),
        HypothesisEvidence(
            finding_key="ecg_ischemia",
            label="Ischemic ECG changes",
            lr=LikelihoodRatioRange(positive_lr=3.6, negative_lr=0.55, positive_lr_low=2.4, positive_lr_high=4.8),
            rationale="Ischemic ECG changes materially increase the likelihood of ACS.",
            provenance_refs=["registry:acs_symptom_profile"],
        ),
        HypothesisEvidence(
            finding_key="hemodynamic_instability",
            label="Hemodynamic instability",
            lr=LikelihoodRatioRange(positive_lr=1.75, negative_lr=0.86, positive_lr_low=1.2, positive_lr_high=2.3),
            rationale="Instability raises concern for high-acuity ACS in the right symptom context.",
            provenance_refs=["registry:acs_symptom_profile"],
        ),
    ],
    "upper_gi_bleed": [
        HypothesisEvidence(
            finding_key="active_gi_bleeding",
            label="Active gastrointestinal bleeding",
            lr=LikelihoodRatioRange(positive_lr=4.0, negative_lr=0.6, positive_lr_low=2.8, positive_lr_high=5.6),
            rationale="Explicit gastrointestinal bleeding language strongly supports an active GI hemorrhage pathway.",
            provenance_refs=["registry:upper_gi_bleed_profile"],
        ),
        HypothesisEvidence(
            finding_key="melena",
            label="Melena",
            lr=LikelihoodRatioRange(positive_lr=5.5, negative_lr=0.55, positive_lr_low=3.8, positive_lr_high=7.2),
            rationale="Melena is a high-yield supportive finding for upper gastrointestinal bleeding.",
            provenance_refs=["registry:upper_gi_bleed_profile"],
        ),
        HypothesisEvidence(
            finding_key="symptomatic_anemia",
            label="Symptomatic anemia",
            lr=LikelihoodRatioRange(positive_lr=2.4, negative_lr=0.75, positive_lr_low=1.6, positive_lr_high=3.1),
            rationale="Symptomatic anemia increases concern for clinically significant blood loss and severity.",
            provenance_refs=["study:cbc_gi_bleed"],
        ),
        HypothesisEvidence(
            finding_key="low_hemoglobin",
            label="Low hemoglobin",
            lr=LikelihoodRatioRange(positive_lr=2.0, negative_lr=0.82, positive_lr_low=1.4, positive_lr_high=2.6),
            rationale="Measured low hemoglobin supports clinically relevant blood loss.",
            provenance_refs=["study:cbc_gi_bleed"],
        ),
        HypothesisEvidence(
            finding_key="severe_anemia",
            label="Severe anemia",
            lr=LikelihoodRatioRange(positive_lr=2.8, negative_lr=0.74, positive_lr_low=2.0, positive_lr_high=3.6),
            rationale="Severe anemia strongly supports significant hemorrhagic burden.",
            provenance_refs=["study:cbc_gi_bleed"],
        ),
        HypothesisEvidence(
            finding_key="anticoagulated",
            label="On anticoagulation",
            lr=LikelihoodRatioRange(positive_lr=2.1, negative_lr=0.8, positive_lr_low=1.4, positive_lr_high=2.8),
            rationale="Active anticoagulation raises the likelihood that ongoing bleeding reflects anticoagulant-associated hemorrhage.",
            provenance_refs=["study:warfarin_bleeding"],
        ),
        HypothesisEvidence(
            finding_key="supratherapeutic_inr",
            label="Supratherapeutic INR",
            lr=LikelihoodRatioRange(positive_lr=2.7, negative_lr=0.82, positive_lr_low=1.8, positive_lr_high=3.6),
            rationale="Supratherapeutic INR increases concern for anticoagulant-amplified hemorrhage.",
            provenance_refs=["study:warfarin_bleeding"],
        ),
        HypothesisEvidence(
            finding_key="pressure_chest_pain",
            label="Pressure-like chest pain",
            lr=LikelihoodRatioRange(positive_lr=0.55, negative_lr=1.05, positive_lr_low=0.35, positive_lr_high=0.8),
            rationale="Primary ischemic chest pain symptoms make GI bleeding a less likely lead explanation.",
            provenance_refs=["registry:upper_gi_bleed_profile"],
        ),
        HypothesisEvidence(
            finding_key="pleuritic_chest_pain",
            label="Pleuritic chest pain",
            lr=LikelihoodRatioRange(positive_lr=0.6, negative_lr=1.02, positive_lr_low=0.4, positive_lr_high=0.85),
            rationale="Pleuritic pain shifts attention toward pulmonary causes over GI hemorrhage.",
            provenance_refs=["registry:upper_gi_bleed_profile"],
        ),
    ],
}
